### ISSUE TITLE
Document Library File Size Restriction is a problem

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#146] opened 2016-09-16 22:22 UTC
Our Conference Manual is 3,910 KB and crashes. Need to have it on our the web site!
(And it will be getting quite a bit larger when I add screen shots of the new software.)

ERROR MESSAGE
This XML file does not appear to have any style information associated with it. The document tree is shown below. (Sending your a separate email of my finding on our DocLib.)
      <Error><Code>ResourceNotFound</Code><Message>The specified resource does not exist.
RequestId:8cf79759-0001-00c0-4864-10ba32000000
Time:2016-09-16T21:48:13.5239292Z</Message></Error>

In response to you email regarding file sizes ... We have in our DocLib:

US Manual Chapter 1 Vincentian History   15,184 KB
US Manual Chapter 2 Vincentian Conferences   20,564 KB
US Manual Chapers 3 Vincentian Spirituality   28,323 KB

All 3 are PDF files. Work fine in LIVE version. All crash in BETA version with above error message.

If this the file size is not enlarged to accommodate these files we won't be able to have them on the site!

**Comment by josephr5000** [comment] 2016-09-16 22:39
DUPLICATE of #145 which I filed before you got to this.

Let's take further discussion over there.  Thanks.

**Closed by josephr5000** 2016-09-16 22:39 UTC
Labels: duplicate
