### ISSUE TITLE
Bug? - Click on (help) for "Age group" and "Ethnicity"

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#228] opened 2016-10-03 06:59 UTC
Click on (help) for "Age group" and "Ethnicity". 

Invokes proper help text with typo. No problem with that.
The help text says that you can check out the "Membership Summary" on the Main Page. No such report is shown on the Main Page. Is this a bug or being left off by mistake?

**Comment by josephr5000** [comment] 2016-10-06 03:00
This is BY DESIGN, and is why #209 should be fixed at some point.

**Closed by josephr5000** 2016-10-06 03:00 UTC
Labels: by design
