### ISSUE TITLE
Modifying the data and time with Refresh - Custom Dates issue

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#158] opened 2016-09-19 20:44 UTC
Select custom dates (works as expected). Click Refresh and that works as expected. At this point the *From* and *To* fields are grayed out and inoperative. You can't move the cursor to either of those 2 fields and select another date range (assuming you wanted to check out another time period).

First, you have to use the down arrow key and select any other date period (with the exception of the Custom Dates selection). Then you need to go back and reinvoke the Custom Dates selection in order to clear the *From* and *To* fields so that different custom dates can be entered.

This condition appears to exist for ALL screens in the program where dates can be changed. It would be more efficient if the intermediate step was not necessary. Sorry, I know this is picky.

![screentom](https://cloud.githubusercontent.com/assets/20777996/18648010/8e28e5da-7e6d-11e6-9db1-820e9e583354.png)

**Comment by josephr5000** [comment] 2016-09-19 21:25
Duplicate of #37.

**Closed by josephr5000** 2016-09-19 21:25 UTC
Labels: duplicate
