### ISSUE TITLE
Input validation

### ISSUE THREAD

**Issue by jln522** [josephr5000/confdb-public#138] opened 2016-09-09 18:31 UTC
Throughout the application:

Input fields whose data is used to produce a report are not being validated for format. alphanumeric, etc.

I suggest that any input field which is used in a report should be validated.
 
 Garbage In Garbage Out

**Comment by josephr5000** [comment] 2016-09-09 18:40
So...request date *is* validated and if you try to enter a non-date it will complain, so I'm not sure I follow your comment "throughout the application".

Could you give a specific example, to help me follow your issue?  Thanks.

**Comment by jln522** [comment] 2016-09-09 20:33
Getting error msg when logging into the text conference? Worked earlier today










Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by josephr5000** [comment] 2016-09-09 20:35
Wondering if a screen shot got omitted.  What "text" conference were you trying?  What error did you get?

**Comment by jln522** [comment] 2016-09-09 21:11
I did not send any screen shots.


[cid:09b8f301-1417-4abc-93c3-e640220f7c10]

[cid:1282632b-8a2f-473b-8e38-f3abaa34a9e1]<http://aka.ms/weboutlook>


________________________________

**Comment by josephr5000** [comment] 2016-09-09 21:14
Okay, but I still don't know what "text" conference you were trying, or what error you got.  More specifics would help me figure out what your issue is.  I can log in fine, so there's something different about your situation but without any detail I can't tell what that might be.

**Comment by jln522** [comment] 2016-09-09 21:52
text is a typo for test



[cid:8a28a66e-835e-481c-8e42-34bf847a8ebe]<http://aka.ms/weboutlook>


________________________________

**Comment by josephr5000** [comment] 2016-09-09 22:07
I'm going to close this as NOT REPRO since as noted above I haven't been able to reproduce either issue you mentioned (validation or login) based on the information you've given me so far.

Feel free to reopen with specifics if the issues you see remain.

**Closed by josephr5000** 2016-09-09 22:07 UTC
Labels: not_repro

**Comment by jln522** [comment] 2016-09-09 23:08
I'm sorry that I given you enough information to reply to my suggestion that important input fields be validated to insure the application can produce accurate and verifiable reports.


Being unable to logon the test db I can't provide more specifics. When I get back on the system I'll be able to be more specific.


Jim


As to the problem I'm having to logon... I'm using the same user, password , and conference on both the live DB and the test DB , and logging on to the live DB logon works OK. I'm not sure this maybe one of those  bugs that only happens rarely when logging on. But  would be a significant problem if users, even occasionally, will not be able to logon.


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by josephr5000** [comment] 2016-09-10 20:18
Reset pw, tested your login successfully, and emailed credentials to you yesterday at 4:37pm.
