### ISSUE TITLE
Reports Detail – Assistance Given 

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#96] opened 2016-08-30 18:57 UTC
Checked to see if I could sort the columns.
Appears broken.  Does NOT allow resorting the list vertically with up and down arrows. Bug?
Clicking Refresh will resort list as expected.

**Comment by josephr5000** [comment] 2016-08-30 19:08
DUPLICATE of #91.  Closing as this doesn't add any further detail.  Please see comments I already wrote on #91.

**Closed by josephr5000** 2016-08-30 19:08 UTC
Labels: duplicate
