### ISSUE TITLE
Question on False on Client File screen

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#100] opened 2016-08-31 20:51 UTC
I created a New Active file on the CC site. Added a request. Filled in required info. Clicked on Done. Got a message saying an email had been sent to me notifying me of the case. I did get that notification in my email but when on clicked on the proper link it gave me the screen below. Two questions: One, why is it shown as still being in the King County Call Center site instead of OL Guadalupe site? Two, what is "within 3 False" at the bottom of the screen?

![kkk](https://cloud.githubusercontent.com/assets/20777996/18145688/22a3f50c-6f81-11e6-9b1a-6a5079d3c2dc.png)

**Comment by josephr5000** [comment] 2016-08-31 21:06
(1) I'm guessing you're still logged into the CC so when you follow the link you see the client's file from the CC perspective.  Can you please log off ConfDB (click Logoff) and then try clicking the email link again?  You should be taken first to a login screen, and if you log in as OLG you should then see the conference version of this client file.  Let me know what happens.

(2) Would you please check OLG's intake setting on how long turnaround is, and let me know?  I'm guessing it is set to "3", but 3 *what*?  3 hours?  3 days?  3 weeks?  or 3 blank?

Thanks

**Comment by TomOwens5000** [comment] 2016-08-31 22:56
NUMBER 1 BELOW

Logged onto test CC site. Entered an address and pressed Lookuup.
Map popped up and displayed target address.
Closed map. Entered Conference (OL Guadalupe).
Put in a Last name (Vector0, First name (John).
Clicked on Add New Client.
Filled in required fields on Add New Client screen.
Clicked Save & Continue after entering the conference.
Clicked Add New Request.
By passed Step 1 by pressing Continue.
ON Step 2 ...  selected Goods - Bus Tickets.
Clicked on Save & Done.
King Country Call Center Client File appeared.
Clicked on Done.
Intake Notifications Sent Successfully - Notifications to Tomo at OL 
Guadalupe screen appeared.
Clicked Continue.
Browse Client Files screen reappeared with all fields blank.
Logged off CC site.

Checked my email. New Intake from Call Center message was there.
Opened the email and the New Intake from Call Center was there as expected.
Clicked on Click here.

The Conference Login... is at 
https://confdb-test.azurewebsites.net/confdb/default.asp?RedirectUrl=%2Fconfdb%2FClientView%2Easp%3FClientID%3D83625
Changed the Conference from CC to OL Guadalupe and logged in.
*Client file did appear as expected! I think before I must have not 
changed from CC to OLG. My BAD but now I understand what happened.*

NUMBER 2 BELOW

The turnaround time was correctly set to 3 days. In fact, time choices 
are: hours, day(s), weeks - and Choose one. 3 blank is not a choice!

**Comment by josephr5000** [comment] 2016-09-02 03:23
Tom's 2nd issue above is related to #105.  Both use the same underlying QuotaMgr code to generate the message.

**Comment by josephr5000** [comment] 2016-09-02 18:13
FIXED.  Pretty sure this is a duplicate of #105.  I can't find a file for Karie Owens in the system, so cannot 100% confirm using your data.  Please check, and reopen with comments if the issue persists.

**Closed by josephr5000** 2016-09-02 18:13 UTC
