### ISSUE TITLE
Notification FAILED

### ISSUE THREAD

**Issue by lisabarrientes** [josephr5000/confdb-public#129] opened 2016-09-06 19:06 UTC
After entering a new request (twice), I received this error. 
![image](https://cloud.githubusercontent.com/assets/22033172/18287038/5b11d8d4-742a-11e6-8875-d6dfd3ee356f.png)

**Comment by josephr5000** [comment] 2016-09-06 19:40
Did you get the follow-up email mentioned in this error that would have given you (as a CC admin) more explanation about what happened?  Thanks.

**Comment by lisabarrientes** [comment] 2016-09-06 19:51
Surprisingly, no…Could it be my email address?

Lisa Barrientes
Helpline Center Manager
St. Vincent de Paul of Seattle|King County
5950 Fourth Avenue South|Seattle, WA 98108
P: 206-767-9975 Ext. 1131
E: lisab@svdpseattle.org<mailto:lisab@svdpseattle.org>

**Comment by josephr5000** [comment] 2016-09-06 20:08
FYI: Please click the "View this issue on GitHub" link and reply there, so the entire email chain doesn't get repeated!

Did you check if (a) your correct email is listed, (b) you are an admin, AND (c) you have verified your email address?  ALL THREE must be true for you to receive notifications.

**Comment by lisabarrientes** [comment] 2016-09-06 20:19
Yes, I verified my email address, and am sure it is correct, because I received that email to verify my email address.  And I am logged in as Admin.

**Comment by josephr5000** [comment] 2016-09-07 07:10
Which conference were you sending this intake to?

**Comment by lisabarrientes** [comment] 2016-09-07 15:01
I sent this to your conference 
![image](https://cloud.githubusercontent.com/assets/22033172/18316899/303d96aa-74d1-11e6-8a15-15e98616d26e.png)

**Comment by josephr5000** [comment] 2016-09-15 06:38
Lisa, have you been able to reproduce this?

You can force a failure by setting intaker on LisaB Conf to blank.  Then log into the CC, go to a file in LisaB Conf, and enter a client request.

If will fail because it tries to notify the intaker at LisaB of the new request you just entered, but there is no intaker assigned.

It doesn't give the full error details on this screen since I *assume* your phone operators wouldn't find that information useful or helpful.  I *assume* (please confirm!) that they just need to know that something happened that that a CC supervisor has been informed.

*You*, the CC supervisor, are the one who's supposed to have received email with clearer details.  Actually it would tell you that notification failed because the LisaB Conf hasn't selected an intaker.  The idea is that you could then call or contact the LisaB conference and help them to fix that.

So, could you please re-try this as I described above, force the error, and let me know if you get email at lisab@svdpseattle.org (I assume that's the verified addr on your CC login?) explaining the error.

**Comment by josephr5000** [comment] 2016-09-19 07:33
I think we found on Friday that this works fine once you verified your email address, so I'm closing this.

**Comment by lisabarrientes** [comment] 2016-09-20 15:34
I think this has to do with what you were talking about the other day, about the assignee.   Here is what was sent to my inbox, as well as others. 

![image](https://cloud.githubusercontent.com/assets/22033172/18677195/dd925666-7f0c-11e6-803c-a7d29ce98329.png)

**Comment by josephr5000** [comment] 2016-09-29 17:39
@lisabarrientes is there still an open issue here?  Thanks.

**Comment by josephr5000** [comment] 2016-10-02 20:08
Haven't heard an answer, so am going to assume there isn't still any issue so I'll close this.  You can re-open if I was mistaken about that.

**Closed by josephr5000** 2016-10-02 20:08 UTC
Labels: not_repro
