### ISSUE TITLE
Change household information - 3 items

### ISSUE THREAD

**Issue by lisabarrientes** [josephr5000/confdb-public#125] opened 2016-09-06 18:27 UTC
•	**Other Adults** – Should be Total Adults (we currently just ask for the total adults in household)
•	**Girls - ages| Boys – ages** – Should be #Kids (we only ask the total of kids in household)
•	**# in household** –Remove (extra step)

**Comment by josephr5000** [comment] 2016-09-07 06:39
This is an area where the conference database -- which the CC is joining -- works differently than what you have been using, so expectations will need to be set differently.

Other Adults is a free-form field that conferences use to record much more than just the # of adults.  Usually you'd use this to record the name(s) of other adult(s) and what relation they have to the caller, eg: "Mark Hatfield (husband)".

Same for Girls - Ages and Boys - Ages.  They are free-form fields that conferences use to flexibly convey whatever information they have about kids, which varies a lot.  Sometimes you just know there are two kids.  Later you may learn the ages and genders, but not the names,  Later still you may learn the names, or at least some of them.

That's why # in Household is a separate item that's intended to capture just the #, nothing else.

I'm going to flag this for DISCUSSION - BY DESIGN.

**Comment by josephr5000** [comment] 2016-09-19 03:34
Reviewing open issues and not sure why this is still open (questions appear to have been answered) so I'm closing it.

**Closed by josephr5000** 2016-09-19 03:34 UTC
Labels: bug, by design
