### ISSUE TITLE
LIVE SITE Adding new client - DOB issue --- can end up with a negative 6 digit number

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#296] opened 2016-10-28 19:26 UTC
One of our conference members discovered this when typing a 4 digit year.
She said it doesn't happen if you only use the last two digits.

I THINK THIS WAS REPORTED EARLIER AND WILL BE A DUPLICATE BUT I DON'T HAVE THE TIME RIGHT NOW TO SEARCH THE TRACKER FOR IT.

**Comment by josephr5000** [comment] 2016-10-31 02:54
Duplicate of #284

**Comment by josephr5000** [comment] 2016-12-12 19:28
Closing since Tom didn't.

**Closed by josephr5000** 2016-12-12 19:28 UTC
Labels: duplicate
