### ISSUE TITLE
Browse Client Files - inconsistent results + Show/Hide Memos & Show/Hide Payment Buttons Issues

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#151] opened 2016-09-17 14:47 UTC
Searched for 2 adults. Brings up list of clients. Some Client Files do show the correct number of adults (searched for 2). Other do not. Some appear to count the boys and/or girls as adults. Results vary depending on which client you select to view (their Client File).

Also, the Show/Hide Memos and Show/Hide Payment Buttons don't appear to do anything. And, yes, I am shown as the Treasurer.
See the screen shots below.

![screen1](https://cloud.githubusercontent.com/assets/20777996/18608916/c08764f8-7caa-11e6-8595-42bd185eb527.png)

![screen2](https://cloud.githubusercontent.com/assets/20777996/18608918/c7ed2ffc-7caa-11e6-9b60-3ce904fdcef4.png)

![screen 3](https://cloud.githubusercontent.com/assets/20777996/18608921/cde353f0-7caa-11e6-958f-36c396cc2c55.png)

**Comment by josephr5000** [comment] 2016-09-18 02:52
BY DESIGN.  The filter says "Other Adult contains", *NOT* "Number of Other Adults equals".

In your example, the text you typed in "Other Adults" on the clients file *does* contain "2" so this is an accurate match.

**Comment by josephr5000** [comment] 2016-09-18 02:54
Show/hide bug already reported by Doug, but FYI if it hadn't been you'd need to have filed it separately to avoid it also being closed BY DESIGN with the main issue above.

**Comment by TomOwens5000** [comment] 2016-09-18 03:32
I think Doug reported the Show/Hide Memos box but NOT the Show/Hide Payment Buttons box which I believed to be different and therefore reported. Maybe they are the same issue but if I remember correctly you wanted us to mention things that appear on different screens as they may be created differently in the code from one screen to another.

Regarding the "2" issue ... guess I missed the point. However, in the screen above it looks to me like 20, not 2. Guess a 2 anywhere in the string is what you are getting at.

**Comment by josephr5000** [comment] 2016-09-18 04:16
FYI no need to reopen, I get email every time you edit the item.

I may have been mistaken about show/hide payment buttons.  If so, please feel free to open a separate issue on that!

Yes, "contains" means anywhere in the string.  "Starts with" means must occur at the beginning.

**Comment by josephr5000** [comment] 2016-09-18 04:24
What do you want to discuss?  Would help others be prepared if you describe your concern.

**Comment by TomOwens5000** [comment] 2016-09-18 04:46
I would like our next online meeting to discuss whether or not the consensus is the showing the actual number of other adults is more useful than just showing a string that contains the number put in the Other Adults contains box.

**Comment by josephr5000** [comment] 2016-09-18 04:55
Thanks.

FYI the point of the "Other Adults" is commonly to contain the *NAME* of other adults in the household -- text, not numbers -- for which a "contains" match is most helpful.  If you want to know the number of people in the household, that would be in the "# in household" field that you see on the Client File page is for.

**Comment by TomOwens5000** [comment] 2016-09-18 05:45
Just looked at an Active Client File on the OLG site.

I don't see "# in household" anywhere. Did you really mean to say 
"Family Size"? I am familiar with and do see that.

**Comment by josephr5000** [comment] 2016-09-18 06:16
Yes I did!

**Comment by josephr5000** [comment] 2016-09-22 19:54
DISCUSSED AT TODAY'S MEETING.  TOM IS OKAY WITH THIS.

**Closed by josephr5000** 2016-09-22 19:54 UTC
Labels: by design
