### ISSUE TITLE
Quota does not work for St. John the Baptist

### ISSUE THREAD

**Issue by lisabarrientes** [josephr5000/confdb-public#287] opened 2016-10-19 17:06 UTC
I set the quota to six, for St. John the Baptist, and sent in two requests.  On the 2nd request, the Status bar was still showing 6 spaces available, and did not show that the client was already on the list. If this is because of the limited edits for those conferences who will only use it to receive calls ONLY, please change it to look like a conference who will be in compliance, and using it like a conference that has full edits, i.e., St. Anthony's Conference. - Otherwise, we (Call Center) cannot see what the quota will reveal, once full. Thanks- Lisa

![image](https://cloud.githubusercontent.com/assets/22033172/19529015/20918a6c-95e3-11e6-946c-b9b782d8bc29.png)

**Comment by drodruck** [comment] 2016-10-20 05:21
I tried this on St. Monica and Mary Queen of Peace.  If you have two requests on the same client, that counts as 1 client for that week.  For a request for another client on that day the quota status shows the proper number of spaces available.  We probably need to test for later days to see if client 1 calls with another request, does that reduce the spaces available which it should not (?).  There are a number of scenarios that we need to consider.

**Comment by josephr5000** [comment] 2016-10-20 06:13
BY DESIGN.  The quota controls the number of *clients* making requests, regardless how many things they request.  One client uses one slot.  Simple :-)

If the same client calls again within the same quota period (same day for daily, same week for weekly, or same month for monthly) they get to add or modify requests because they've already been granted a slot.

If that clients wants to make a new request in a fresh quota period (different day, different week, or different month) they'll only be able to if there is a quota slot available for them.

The current helpline DB behaves this way too.

**Comment by lisabarrientes** [comment] 2016-10-20 13:57
Okay, I know how the current database goes.  But what I'm talking about is (and what is showing on the screenshot) is, this is a Request #2 from a **totally different client.**  it does not show that there was a previous request put in _from what I put in previously before this client._  Also, I noticed that in some cases on the same client it went down to 5 for the quota from 6, but that's it.  It did nothing else, It just is not working properly.

**Comment by josephr5000** [comment] 2016-10-20 16:29
Oops, I misunderstood!  Saw your image above of a single client with two requests and thought that's what you were talking about.  Let me investigate...

**Comment by lisabarrientes** [comment] 2016-10-20 16:50
Thank you.

**Comment by josephr5000** [comment] 2018-01-18 22:26
Since quotas are apparently no longer being used, I'm closing this as WON'T FIX.

**Closed by josephr5000** 2018-01-18 22:26 UTC
Labels: feature-call-center, issue-bug, resolved-wont-fix

**Comment by lisabarrientes** [comment] 2018-01-19 19:03
Correction:

Quotas are still being used, by those who were grandfathered into it. Although, I do not see an option for a quota on the current menu.

But you can still close this as I no longer see the issue happening.

Thank you,

Lisa
