### ISSUE TITLE
Enhancement Request - on logging on the the database allow hitting the Enter key to advance to the next field

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#220] opened 2016-10-03 01:26 UTC
Looks like this works this way for the Call Center site.
Once all three fields contain the correct information, hitting Enter would log you in.
Again, not a high priority but it would be nice.

**Comment by josephr5000** [comment] 2016-10-03 02:09
Want to close this as BY DESIGN.  I assume you're asking about the login screen.  Typically when selecting things in a dropdown list (eg: conference name) you use the arrow keys to navigate and ENTER to accept that one choice -- the dropdown -- but not to accept ALL three of your choices.  In this respect dropdown lists behave differently from freeform fields where you type stuff, like the username and password fields.  So...just press TAB to advance focus to the login button, then press ENTER, and you'll be good to go.  It's not always good to muck with expected keyboard behavior.

**Comment by TomOwens5000** [comment] 2016-10-03 02:27
Think I did not explain this well.
On logging on to the database one needs to provide their Username, Password and Conference. Those are the 3 things am I talking about - not any 3 things in the dropdown list of conferences. For example:
Username: enter tomo and hit the Enter key. The cursor would now be in the Password field.
Type the password and press the Enter key. The cursor would now be in the Conference field.
Now select the proper conference from the dropdown list. Once the selected conference is in the Conference field press the Enter key to automatically be logged in WITHOUT have to click on the LOGIN key.

**Comment by josephr5000** [comment] 2016-10-03 02:29
You explained it perfectly.

That's just not how dropdown lists usually work with a keyboard.  That's my point, and why I'm not keen to change this.

Please re-read my explanation closely.

**Closed** 2016-10-03 02:35 UTC
Labels: by design, enhancement
