### ISSUE TITLE
Call Center - a user login goes directly to the Browse Client Files screen ... Main Page is incorrect label

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#200] opened 2016-09-28 16:43 UTC
Users have NO access to the Main Page - only Administrators do.
When a user logs on they go directly to the "Browse Client Files" screen.
It has two labels on the right side of the screen: Main Page and Logoff.
For a user, the Main Page label should be changed to "Refresh" or "Clear" since clicking on Main Page serves only to clear all the fields (which is fine). So, in essence, all it does is refresh the screen with blank fields.

**Comment by josephr5000** [comment] 2016-10-02 19:42
Set prio=like.  Would be nice to fix, but not essential.

**Comment by TomOwens5000** [comment] 2016-10-03 02:09
Suggest a SHOULD classification for this one.

**Comment by josephr5000** [comment] 2016-10-03 02:26
Duplicate of #153.  Closing since we don't need two items on the same topic.

**Closed by josephr5000** 2016-10-03 02:26 UTC
Labels: bug, duplicate, like (prio)
