### ISSUE TITLE
Call Center - Helpline Settings failure

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#202] opened 2016-09-28 17:06 UTC
Clicking on Helpline Settings produces the follow error message:
The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

**Comment by josephr5000** [comment] 2016-09-29 20:13
Prioritized and added to NEXT UP list

**Comment by josephr5000** [comment] 2016-10-01 04:13
Duplicate of #190

**Closed by josephr5000** 2016-10-01 04:13 UTC
Labels: bug, duplicate
