### ISSUE TITLE
Page Not Found

### ISSUE THREAD

**Issue by jln522** [josephr5000/confdb-public#28] opened 2016-07-25 16:55 UTC
Numerous Files - Record Hours,Member Report,Volunteer Hours,Frequent Callers,Bed Nights,Document Library

**Comment by josephr5000** [comment] 2016-07-25 17:42
Hi Jim,
Over lunch let's talk about an issue report template.
It's very helpful to me in terms of being able to quickly identify what testers are concerned about if some key items are included.
Typically I've done something like this.  This isn't set in stone...I'm just offering it as a starting point for discussion.
ENVIRONMENT- What server (DEV/TEST/LIVE) were you using- What browser are you using?  (eg: Edge, Firefox, Chrome, Opera, Safari, ...)- What OS / device are you using?  (eg: iPad, Galaxy S7 phone, Windows 10 laptop, ...)
STEPS TO REPRODUCE- List step-by-step what you did.  Sometimes testers will need to go back and try to repeat the error to get this clear, but that's helpful and valuable.
RESULT- Identify precisely what happened that you found surprising. "Doesn't work" isn't very descriptive.  Did you get an error message, and if so, what?  Or did it hang forever?  Or...what?

EXPECTED- Say what you expected to have happen. This is important because something may not actually be a bug. The tester's expectation may have been incorrect, or this may point to a UI or design flaw that made proper operation less obvious than it should be.
ALSO NOTE- Optional. Include in case there are any other relevant remarks to include.
Joseph

**Comment by josephr5000** [comment] 2016-07-25 18:00
FIXED
Record Hours
Volunteer Hours

NOT REPRO
Member Report
Frequent Callers
Bed Nights

SEPARATE ISSUE
Document Library: folder/file navigation works fine. Clicking a leaf node to actually access the file fails as actual files need to be ported to Azure.  This is a separate work item.

**Comment by josephr5000** [comment] 2016-07-25 18:03
Reopening. Have invited JLN522 as collaborator and will assign to him when he accepts.

**Comment by josephr5000** [comment] 2016-08-08 23:23
No response from jln522 after 2 weeks.  Closing.

**Closed by josephr5000** 2016-08-08 23:23 UTC
Labels: bug, fixed, Hotfix
