### ISSUE TITLE
Can't complete the email verification 

### ISSUE THREAD

**Issue by DaveSherwood** [josephr5000/confdb-public#191] opened 2016-09-27 17:22 UTC
I have made many attempts to complete the email verification from the profile in the call center when logging in as an administrator (ccdaves).
I do receive an email and it contains a link to click on to verify the email. When I click on it, it opens up the logon screen for the database and stops there. And my profile never gets updated. So any tests related to having this email address verified cannot be accomplished.

**Comment by josephr5000** [comment] 2016-09-27 17:36
Okay, what happens *after* you log in?

**Comment by josephr5000** [comment] 2016-09-27 17:37
To be more clear, I'm wondering whether the problem is that verification *fails* or if you just don't know what to do when presented with a login screen as that isn't something you're expecting?

**Comment by DaveSherwood** [comment] 2016-09-27 17:43
It was not what I was expecting. I will try it again. The notifications seem to have expired. 
Dave 

----- Original Message -----

**Comment by DaveSherwood** [comment] 2016-09-27 17:53
Chock it up to operator error, or ignorance. I successfully completed the verification and I checked my profile and it shows verified. I will go complete the last of my tests. 

Dave 

----- Original Message -----

**Comment by TomOwens5000** [comment] 2016-09-27 19:17
I have made many attempts to complete the email verification from the profile in the call center when logging in as an administrator (cctomo).
I do NOT receive an email with a link to click on to verify the email. This whole thing appear broken as far as an Administrator able to get it to work.

**Comment by josephr5000** [comment] 2016-10-01 02:57
Tom has a separate issue open regarding his concerns.  Dave's issue reported above appears to be solved, and the requirement to log in when verifying is by design, so I'm going to close this.

**Closed by josephr5000** 2016-10-01 02:57 UTC
Labels: by design
