### ISSUE TITLE
Database Settings - Quota

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#70] opened 2016-08-24 18:51 UTC
Broken. Made edits, clicked on Save and got the following error message: The page cannot be displayed because an internal server error has occurred.

Not sure which field I edited that caused the problem. Likely editing any of the fields does it. Comment: when going from one choice to another it would make sense to clear all fields that no longer apply. For example, if Unlimited is checked clear all the other fields. Not sure about adding information in days fields at bottom of screen. Crashed before I could establish whether or not they work.

![quota](https://cloud.githubusercontent.com/assets/20777996/17943594/ee64fb50-69f0-11e6-88eb-10b37e6646b3.png)

**Comment by josephr5000** [comment] 2016-09-03 01:10
DUPLICATE.

I think #94 (which I just fixed) is a duplicate of this, so I'm closing this.  Reopen with comments if you disagree.

**Closed by josephr5000** 2016-09-03 01:10 UTC
Labels: duplicate
